---
title: "Homework_4"
author: "Juliana Dau"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Problem 1

#a. 
```{r}
x = 1.1
a = 2.2 
b = 3.3
z=x ^ (a^b)
print(z)
# result of z was 3.61714012551594
```
#b
```{r}
 
x = 1.1
a = 2.2 
b = 3.3
z=(x^a) ^ b
print(z)
```

#c.
```{r}
x = 1.1
a = 2.2 
b = 3.3
z= 3*(x^3) + 2*(x^2) + 1
print(z)

```
Problem 2
#a
```{r}

vector_a<-c(1:8,7:1)
print(vector_a)
```
#b
```{r}
vector_b <- rep(x=1:5,times=1:5)
print(vector_b)
```

```{r}
vector_c <- rep(x=5:1,times=1:5)
print(vector_c)

```
Problem 3
```{r}
library(ggplot2) 
set.seed(2)
z <- runif(2) 
qplot(x=z)
x=0.185
y=0.701
r= sqrt(x^2+y^2)
print(r)
theta=atan(y/x)
print(theta)

```
#observation that tan^1=atan function 

# Problem 4
# General set up of the queue

```{r}
queue <- c("sheep", "fox", "owl", "ant")
z2 <- c("sheep"=1, "fox"=2, "owl"=3, "ant"=4)

print(z2)

```
#a
```{r}
queue <- c("sheep", "fox", "owl", "ant", "serpent")
z2 <- c("sheep"=1, "fox"=2, "owl"=3, "ant"=4, "serpent"=5 )
print(z2)
```

#b
```{r}
z2 <- c("fox"=1, "owl"=2,  "ant"=3, "serpent"=4 )
print(z2)
```
#c
```{r}
z2 <- c("donkey"=1, "fox"=2, "owl"=3, "ant"=4, "serpent"=5 )
print(z2)
```
#d
```{r}
z2 <- c("donkey"=1, "fox"=2, "ant"=3)
print(z2)
```
#e
```{r}
z2 <- c("sheep"=1, "fox"=2, "ant"=3, "serpent"=4 )
print(z2)
```
#f
```{r}
z2 <- c("sheep"=1, "fox"=2, "aphid"=3, "ant"=4, "serpent"=5 )
print(z2)
```
#g
```{r}
# Third position 
```
# Problem 5.
```{r}
x<-1:100
which(x%%2!=0 & x%%3!=0 & x%%7!=0)
```