---
title: "Homework-9"
author: "Juliana Dau"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#R script Homework 9 March 26_2025
library(devtools)
install_github('ngotelli/upscaler')
library(upscaler)
library(stringr)
library(tidyverse)
library(sqldf)
```

```{r}
x<-list.files("C:/Users/jujud/OneDrive/Documentos/Computational Biology/Assignments")
subfolders <- x
for(i in 1:10){
  print(x[i])
  CleanedData<-list.files(
    path = list.files(),
    pattern=".brd_countdata.",
    full.names=TRUE)
  print(CleanedData)
}
```
```{r}
years <- (2015:2023)

for (i in 1:10) {
  print(CleanedData[i])
  raw_data <- read.csv(CleanedData[i], na.strings = c("","NA")) 
  clean_data <- raw_data[complete.cases(raw_data["scientificName"]),                ] 
  write.csv(CleanedData,paste0("CleanedData", years[i], ".csv"))

}
```
```{r}
glimpse(clean_data)

```
#To try to calculate abundance and richness per year tried to add a colunm with the year that is linked to the file but wasn`t able to troubleshoot. 





 